routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/', 'IndexController')->name('index');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs.index')->middleware('can:view logs');
	Route::get('users/{user}/permissons', 'UserController@showPermissions')->name('users.showPermissions');
	Route::post('users/{user}/permissons/', 'UserController@givePermissions')->name('users.givePermissions');
	Route::resource('users', 'UserController');
	Route::resource('branches', 'BranchController');
	Route::resource('transits', 'TransitController');
	Route::resource('risks', 'RiskController');
	Route::post('/cover-notes/{coverNote}/download', 'CoverNoteController@download')->name('cover-notes.download');
	Route::resource('cover-notes', 'CoverNoteController')->parameters(['cover-notes' => 'coverNote']);
});

resources/views/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="{{ env('APP_NAME') }} - Insurance Cover Note & Policy Generator">
    <meta name="author" content="Tariq Imtinan">
    <meta name="keyword" content="Insurance, Cover Note, Policy, {{ env('APP_NAME') }}">
    <title>{{ env('APP_NAME') }} - @yield('title')</title>
    <meta name="theme-color" content="#ffffff">
    <!-- Main styles for this application-->
    <link href="{{ asset('/coreui/css/style.css') }}" rel="stylesheet">

    @yield('head-styles')
</head>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('title', 'Dashboard')

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item active">Dashboard</li>
</ol>
@endsection

@section('content')
  <div class="fade-in">
		<div class="row">
	    <div class="col-sm-6 col-lg-3">
	      <div class="card text-white bg-gradient-primary">
	        <div class="card-body card-body pb-5 d-flex justify-content-between align-items-start">
	          <div>
	            <div class="text-value-lg">{{ $coverNotes }}</div>
	            <div>Issued Cover Notes</div>
	          </div>
	        </div>
	      </div>
	    </div>
	    <!-- /.col-->
	    <div class="col-sm-6 col-lg-3">
	      <div class="card text-white bg-gradient-primary">
	        <div class="card-body card-body pb-5 d-flex justify-content-between align-items-start">
	          <div>
	            <div class="text-value-lg">{{ $branches }}</div>
	            <div>Branch Offices</div>
	          </div>
	        </div>
	      </div>
	    </div>
	    <!-- /.col-->
	    <div class="col-sm-6 col-lg-3">
	      <div class="card text-white bg-gradient-primary">
	        <div class="card-body card-body pb-5 d-flex justify-content-between align-items-start">
	          <div>
	            <div class="text-value-lg">{{ $users }}</div>
	            <div>Users</div>
	          </div>
	        </div>
	      </div>
	    </div>
	    <!-- /.col-->
	    <div class="col-sm-6 col-lg-3">
	      <div class="card text-white bg-gradient-primary">
	        <div class="card-body card-body pb-5 d-flex justify-content-between align-items-start">
	          <div>
	            <div class="text-value-lg">{{ $risks }}</div>
	            <div>Risk Coverages</div>
	          </div>
	        </div>
	      </div>
	    </div>
	    <!-- /.col-->
	  </div>
  </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  @include('head')
  
  @section('body')
    <body class="c-app">

      @include('sidebar')

      <div class="c-wrapper c-fixed-components">
        <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
          <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
            <svg class="c-icon c-icon-lg">
              <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-menu') }}"></use>
            </svg>
          </button>
          
          <h5 class="c-header-brand d-lg-none">{{ env('APP_NAME') }}</h5>

          <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
            <svg class="c-icon c-icon-lg">
              <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-menu') }}"></use>
            </svg>
          </button>
          <ul class="c-header-nav ml-auto mr-4">
            <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <div class="c-avatar"><img class="c-avatar-img" src="{{ asset('/coreui/assets/img/avatars/person-icon.png') }}"></div>
              </a>
              <div class="dropdown-menu dropdown-menu-right pt-0">
                <div class="dropdown-header bg-light py-2"><strong>@auth {{ Auth::user()->name }} @endauth</strong></div><a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
                  <svg class="c-icon mr-2">
                    <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-account-logout') }}"></use>
                  </svg> {{ __('Logout') }}</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                      @csrf
                  </form>
              </div>
            </li>
          </ul>
          <div class="c-subheader px-3">
            <!-- Breadcrumb-->
            @yield('breadcrumb')
            <!-- Breadcrumb Menu-->
          </div>
        </header>
        <div class="c-body">
          <main class="c-main">
            <div class="container-fluid">
              <div class="fade-in">
                @if (session('status'))
                  <div class="alert alert-success">
                    {{ session('status') }}
                  </div>
                @endif
                @if ($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif
                @yield('content')
              </div>
            </div>
          </main>
          <footer class="c-footer">
            <div>© {{ now()->year }} Tariq Imtinan</div>
          </footer>
        </div>
      </div>
      <!-- CoreUI and necessary plugins-->
      <script src="{{ asset('/coreui/vendors/@coreui/coreui/js/coreui.bundle.min.js') }}"></script>
      <!--[if IE]><!-->
      <script src="{{ asset('/coreui/vendors/@coreui/icons/js/svgxuse.min.js') }}"></script>
      <!--<![endif]-->

      @yield('tail-scripts')
    </body>
  @show
</html>

resources/views/sidebar.blade.php
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
  <div class="c-sidebar-brand d-lg-down-none">
    <h5 class="c-sidebar-brand-full">{{ env('APP_NAME') }}</h5>
    <h5 class="c-sidebar-brand-minimized">{{ env('APP_NAME') }}</h5>
  </div>
  <ul class="c-sidebar-nav">
    <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('index') }}">
      <svg class="c-sidebar-nav-icon">
        <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-speedometer') }}"></use>
      </svg> Dashboard</a>
    </li>
    @canany(['create users', 'view users'])
      <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Users</a>
        <ul class="c-sidebar-nav-dropdown-items">
          @can('view users')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('users.index') }}"><span class="c-sidebar-nav-icon"></span> List</a></li>
          @endcan
          @can('create users')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('users.create') }}"><span class="c-sidebar-nav-icon"></span> Create</a></li>
          @endcan
        </ul>
      </li>
    @endcanany
    @canany(['create cover notes', 'view cover notes'])
      <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Cover Notes</a>
        <ul class="c-sidebar-nav-dropdown-items">
          @can('view cover notes')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('cover-notes.index') }}"><span class="c-sidebar-nav-icon"></span> List</a></li>
          @endcan
          @can('create cover notes')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('cover-notes.create') }}"><span class="c-sidebar-nav-icon"></span> Create</a></li>
          @endcan
        </ul>
      </li>
    @endcanany
    @can('view logs')
      <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('logs.index') }}" target="_blank">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Activity Logs</a>
      </li>
    @endcan
    @canany(['create branches', 'view branches'])
      <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Branches</a>
        <ul class="c-sidebar-nav-dropdown-items">
          @can('view branches')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('branches.index') }}"><span class="c-sidebar-nav-icon"></span> List</a></li>
          @endcan
          @can('create branches')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('branches.create') }}"><span class="c-sidebar-nav-icon"></span> Create</a></li>
          @endcan
        </ul>
      </li>
    @endcanany
    @canany(['create transits', 'view transits'])
      <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Transits</a>
        <ul class="c-sidebar-nav-dropdown-items">
          @can('view transits')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('transits.index') }}"><span class="c-sidebar-nav-icon"></span> List</a></li>
          @endcan
          @can('create transits')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('transits.create') }}"><span class="c-sidebar-nav-icon"></span> Create</a></li>
          @endcan
        </ul>
      </li>
    @endcanany
    @canany(['create risks', 'view risks'])
      <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
        <svg class="c-sidebar-nav-icon">
          <use xlink:href="{{ asset('/coreui/vendors/@coreui/icons/svg/free.svg#cil-star') }}"></use>
        </svg> Risks</a>
        <ul class="c-sidebar-nav-dropdown-items">
          @can('view risks')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('risks.index') }}"><span class="c-sidebar-nav-icon"></span> List</a></li>
          @endcan
          @can('create risks')
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{ route('risks.create') }}"><span class="c-sidebar-nav-icon"></span> Create</a></li>
          @endcan
        </ul>
      </li>
    @endcanany

  </ul>
  <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>