routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/', 'IndexController')->name('index');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs.index')->middleware('can:view logs');
	Route::get('users/{user}/permissons', 'UserController@showPermissions')->name('users.showPermissions');
	Route::post('users/{user}/permissons/', 'UserController@givePermissions')->name('users.givePermissions');
	Route::resource('users', 'UserController');
	Route::resource('branches', 'BranchController');
	Route::resource('transits', 'TransitController');
	Route::resource('risks', 'RiskController');
	Route::post('/cover-notes/{coverNote}/download', 'CoverNoteController@download')->name('cover-notes.download');
	Route::resource('cover-notes', 'CoverNoteController')->parameters(['cover-notes' => 'coverNote']);
});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\UuidTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, UuidTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Permission;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\{
    Hash,
    Redirect,
    View,
    Log,
};

class UserController extends Controller
{
    private $user;
    private $permission;
    
    function __construct(User $user, Permission $permission)
    {
        $this->user = $user;
        $this->permission = $permission;

        $this->authorizeResource(User::class, 'user');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->user->paginate(10);

        return View::make('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = $this->user->create([
            'name' => request('name'),
            'email' => request('email'),
            'password' => Hash::make(request('password'))
        ]);

        return Redirect::route('users.show', $user->id)->with('status', 'User created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return View::make('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return View::make('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        $user->update([
            'name' => request('name'),
            'email' => request('email'),
            'password' => Hash::make(request('password'))
        ]);

        return Redirect::route('users.show', $user->id)->with('status', 'User updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return Redirect::route('users.index')->with('status', 'User deleted.');
    }

    /**
     * Show all permission of a user
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    
    public function showPermissions(User $user)
    {
        $permissions = $this->permission->all();

        return View::make('users.permissions', compact('permissions', 'user'));
    }

    /**
     * Give permissions to a user
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    
    public function givePermissions(User $user)
    {
        $newPermissions = request()->except('_token');
        $oldPermissions = $user->permissions;
        $user->syncPermissions($newPermissions);

        Log::channel('users')->info("User account permissions updated for $user->name.", ['email' => $user->email, 'user_id' => $user->id, 'updated_by' => auth()->user()->name . " (user_id: " . auth()->user()->id . ")", 'old_permissions' => $oldPermissions->pluck('name'), 'new_permissions' => $user->permissions->pluck('name')]);

        return Redirect::route('users.showPermissions', $user)->with('status', 'Permission settings updated.');
    }
}

app/Http/Livewire/Users/Create.php
<?php

namespace App\Http\Livewire\Users;

use App\Models\User;
use Livewire\Component;

class Create extends Component
{
	public $name, $email, $password, $password_confirmation;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.create');
    }
}

app/Http/Livewire/Users/Edit.php
<?php

namespace App\Http\Livewire\Users;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $user, $name, $email, $password, $password_confirmation;

	public function mount()
	{
		$this->fill([
			'name' => $this->user->name,
			'email' => $this->user->email
		]);
	}

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($this->user)],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.edit');
    }
}

resources/views/users/create.blade.php
@extends('layout')

@section('title', 'Create User')

@section('head-styles')
  @livewireStyles
@endsection

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item">Dashboard</li>
  <li class="breadcrumb-item">Users</li>
  <li class="breadcrumb-item active">Create</li>
</ol>
@endsection

@section('content')
<div class="col-md-10">
  <div class="card">
    <div class="card-header">Create<strong> User</strong></div>
    <div class="card-body">
      <livewire:users.create />
    </div>
  </div>
</div>
@endsection

@section('tail-scripts')
  @livewireScripts
@endsection

resources/views/users/edit.blade.php
@extends('layout')

@section('title', 'Edit User')

@section('head-styles')
  @livewireStyles
@endsection

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item">Dashboard</li>
  <li class="breadcrumb-item">Users</li>
  <li class="breadcrumb-item active">Edit</li>
</ol>
@endsection

@section('content')
<div class="col-md-10">
  <div class="card">
    <div class="card-header">Edit<strong> User</strong></div>
    <div class="card-body">
      <livewire:users.edit :user="$user" />
    </div>
  </div>
</div>
@endsection

@section('tail-scripts')
  @livewireScripts
@endsection

resources/views/users/index.blade.php
@extends('layout')

@section('title', 'Users')

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item">Dashboard</li>
  <li class="breadcrumb-item active">Users</li>
</ol>
@endsection

@section('content')
<div class="col-lg-12">
  <div class="card">
    <div class="card-header"><i class="fa fa-align-justify"></i> Users</div>
    <div class="card-body">
      <table class="table table-responsive-sm table-bordered table-striped table-sm">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
            <tr>
              <td><a href="{{ route('users.show', $user->id) }}">{{ $user->id }}</a></td>
              <td>{{ $user->name }}</td>
              <td>{{ $user->email }}</td>
              <td>{{ $user->created_at }}</td>
              <td>{{ $user->updated_at }}</td>
              <td>
                @can('update users')
                  <a href="{{ route('users.edit', $user->id) }}">Edit</a><br>
                  <a href="{{ route('users.showPermissions', $user->id) }}">Permission Settings</a><br>
                @endcan
                @can('delete users')
                  <a href="#" class="text-danger" type="button" data-toggle="modal" data-target="#dangerModal{{ $user->id }}">Delete</a>

                  <div class="modal fade" id="dangerModal{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="deleteCoverNote" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-danger" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Warning</h4>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        </div>
                        <div class="modal-body">
                          <p>This action will delete user {{ $user->id }}. Are you sure?</p>
                        </div>
                        <div class="modal-footer">
                          <form method="POST" action="{{ route('users.destroy', $user->id) }}">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                            <button class="btn btn-danger" type="submit">Yes, Delete!</button>
                          </form>
                        </div>
                      </div>
                      <!-- /.modal-content-->
                    </div>
                    <!-- /.modal-dialog-->
                  </div>
                @endcan
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      {{ $users->links() }}
    </div>
  </div>
</div>
@endsection

resources/views/users/permissions.blade.php
@extends('layout')

@section('title', 'Edit User Permissions')

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item">Dashboard</li>
  <li class="breadcrumb-item">Users</li>
  <li class="breadcrumb-item">{{ $user->id }}</li>
  <li class="breadcrumb-item active">Permissions</li>
</ol>
@endsection

@section('content')
<div class="col-md-10">
  <div class="card">
    <div class="card-header">Edit<strong> User Permissions</strong></div>
    <div class="card-body">
      <form class="form-horizontal" action="{{ route('users.givePermissions', $user->id) }}" method="post">
        @csrf
        @foreach ($permissions as $permission)
          <div class="form-check form-check-inline mr-1 mb-2">
            <input class="form-check-input" id="{{ $permission->id }}" name="permission{{ $permission->id }}" type="checkbox" value="{{ $permission->name }}" @if ($user->permissions->contains($permission)) checked @endif>
            <label class="form-check-label" for="{{ $permission->id }}" style="text-transform: capitalize">{{ $permission->name }}</label>
          </div><br>
        @endforeach
        <div class="card-footer mt-3">
          <button class="btn btn-sm btn-primary" type="submit"> Submit</button>
          <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layout')

@section('title', "User - $user->id")

@section('breadcrumb')
<ol class="breadcrumb border-0 m-0">
  <li class="breadcrumb-item">Dashboard</li>
  <li class="breadcrumb-item">Users</li>
  <li class="breadcrumb-item active">{{ $user->id }}</li>
</ol>
@endsection

@section('content')
<div class="col-lg-12">
  <div class="card">
    <div class="card-header"><i class="fa fa-align-justify"></i> User Details</div>
    <div class="card-body">
      <table class="table table-responsive table-borderless">
        <tbody>
          <tr>
            <th scope="row" colspan="4">Id</th>
            <td>{{ $user->id }}</td>
          </tr>
          <tr>
            <th scope="row" colspan="4">Name</th>
            <td>{{ $user->name }}</td>
          </tr>
          <tr>
            <th scope="row" colspan="4">Email</th>
            <td>{{ $user->email }}</td>
          </tr>
          <tr>
            <th scope="row" colspan="4">Email Verified At</th>
            <td>{{ $user->email_verified_at }}</td>
          </tr>
            <th scope="row" colspan="4">Created At</th>
            <td>{{ $user->created_at }}</td>
          </tr>
          <tr>
            <th scope="row" colspan="4">Updated At</th>
            <td>{{ $user->updated_at }}</td>
          </tr>
        </tbody>
      </table>
      <hr>
      @can('update users')
        <a href="{{ route('users.edit', $user->id) }}"><button class="btn btn-primary">Edit</button></a>
        <a href="{{ route('users.showPermissions', $user->id) }}"><button class="btn btn-primary">Permission Settings</button></a>
      @endcan
    </div>
  </div>
</div>
@endsection