routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/', 'IndexController')->name('index');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs.index')->middleware('can:view logs');
	Route::get('users/{user}/permissons', 'UserController@showPermissions')->name('users.showPermissions');
	Route::post('users/{user}/permissons/', 'UserController@givePermissions')->name('users.givePermissions');
	Route::resource('users', 'UserController');
	Route::resource('branches', 'BranchController');
	Route::resource('transits', 'TransitController');
	Route::resource('risks', 'RiskController');
	Route::post('/cover-notes/{coverNote}/download', 'CoverNoteController@download')->name('cover-notes.download');
	Route::resource('cover-notes', 'CoverNoteController')->parameters(['cover-notes' => 'coverNote']);
});

app/Http/Controllers/CoverNoteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CoverNoteRequest;
use App\Models\Branch;
use App\Models\CoverNote;
use App\Models\Risk;
use App\Models\Transit;
use App\Services\CoverNoteGeneratorService;
use Illuminate\Support\Facades\{
    View,
    Redirect
};

class CoverNoteController extends Controller
{
    private $branch;
    private $coverNote;
    private $risk;
    private $transit;
    private $coverNoteGeneratorService;

    function __construct(CoverNote $coverNote, Branch $branch, Risk $risk, Transit $transit, CoverNoteGeneratorService $coverNoteGeneratorService)
    {
        $this->branch = $branch;
        $this->coverNote = $coverNote;
        $this->risk = $risk;
        $this->transit = $transit;
        $this->coverNoteGeneratorService = $coverNoteGeneratorService;

        $this->authorizeResource(CoverNote::class, 'coverNote');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coverNotes = $this->coverNote->paginate(10);

        return View::make('cover-notes.index', compact('coverNotes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branches = $this->branch->all();
        $risks = $this->risk->all();
        $transits = $this->transit->all();

        return View::make('cover-notes.create', compact('branches', 'risks', 'transits'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CoverNoteRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CoverNoteRequest $request)
    {
        $preparedDataArray = $this->coverNote->prepareDataForInsertion($request);
        $coverNote = $this->coverNote->create($preparedDataArray['dataToInsert']);
        $coverNote->risks()->attach($preparedDataArray['risks']);
        $coverNote->transits()->attach($preparedDataArray['transits']);

        return Redirect::route('cover-notes.show', $coverNote->id)->with('status', 'Cover Note created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CoverNote  $coverNote
     * @return \Illuminate\Http\Response
     */
    public function show(CoverNote $coverNote)
    {
        return View::make('cover-notes.show', compact('coverNote'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\CoverNote  $coverNote
     * @return \Illuminate\Http\Response
     */
    public function edit(CoverNote $coverNote)
    {
        $branches = $this->branch->all();
        $risks = $this->risk->all();
        $transits = $this->transit->all();

        return View::make('cover-notes.edit', compact('coverNote', 'branches', 'risks', 'transits'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CoverNoteRequest  $request
     * @param  \App\Models\CoverNote  $coverNote
     * @return \Illuminate\Http\Response
     */
    public function update(CoverNoteRequest $request, CoverNote $coverNote)
    {
        $preparedDataArray = $this->coverNote->prepareDataForInsertion($request);
        $coverNote->update($preparedDataArray['dataToInsert']);
        $coverNote->risks()->sync($preparedDataArray['risks']);
        $coverNote->transits()->sync($preparedDataArray['transits']);

        return Redirect::route('cover-notes.show', $coverNote->id)->with('status', 'Cover Note upated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CoverNote  $coverNote
     * @return \Illuminate\Http\Response
     */
    public function destroy(CoverNote $coverNote)
    {
        $coverNote->transits()->detach();
        $coverNote->risks()->detach();
        $coverNote->delete();

        return Redirect::route('cover-notes.index')->with('status', 'Cover Note Deleted!');
    }

    public function download(CoverNote $coverNote)
    {
        $fileType = request('fileType');
        
        $this->coverNoteGeneratorService->generate($coverNote, $fileType);
    }
}

app/Http/Livewire/Branches/Create.php
<?php

namespace App\Http\Livewire\Branches;

use Livewire\Component;

class Create extends Component
{
	public $name, $email, $address, $phone_number, $fax_number;

	protected function rules()
    {
        return [
            'name' => 'required|string|min:2|max:255|unique:branches',
            'address' => 'required|string|min:10',
            'phone_number' => 'required|string|max:20|unique:branches',
            'fax_number' => 'required|string|max:20|unique:branches',
            'email' => ['required', 'string', 'email', 'max:255', 'unique:branches']
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.branches.create');
    }
}

app/Http/Livewire/Branches/Edit.php
<?php

namespace App\Http\Livewire\Branches;

use Livewire\Component;
use Illuminate\Validation\Rule;

class Edit extends Component
{
	public $branch, $name, $email, $address, $phone_number, $fax_number;

	public function mount()
	{
		$this->fill([
			'name' => $this->branch->name,
			'email' => $this->branch->email,
			'address' => $this->branch->address,
			'phone_number' => $this->branch->phone_number,
			'fax_number' => $this->branch->fax_number
		]);
	}

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('branches')->ignore($this->branch)],
            'address' => ['required', 'string', 'min:10'],
            'phone_number' => ['required', 'string', 'max:20', Rule::unique('branches')->ignore($this->branch)],
            'fax_number' => ['required', 'string', 'max:20',  Rule::unique('branches')->ignore($this->branch)],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('branches')->ignore($this->branch)]
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.branches.edit');
    }
}

app/Http/Livewire/CoverNotes/Create.php
<?php

namespace App\Http\Livewire\CoverNotes;

use Livewire\Component;

class Create extends Component
{
    public $branches;
    public $risks;
    public $transits;
    public $issuing_office;
    public $insured_bank_name;
	public $insured_bank_address;
	public $insured_bank_account_name;
	public $insured_address;
	public $interest_covered;
	public $voyage_from;
	public $voyage_to;
	public $voyage_via;
	public $amount_insured_usd;
	public $amount_insured_tolerance;
	public $usd_to_bdt_rate;
	public $mr_no;
	public $vat_rate;
	public $stamp_duty_bdt;

    protected function rules()
    {
        return [
            'issuing_office' => ['required', 'string'],
            'insured_bank_name' => ['required', 'string', 'min:2', 'max:255'],
            'insured_bank_address' => ['required', 'string', 'min:10', 'max:255'],
            'insured_bank_account_name' => ['required', 'string', 'max:255'],
            'insured_address' => ['required', 'string', 'min:10', 'max:255'],
            'interest_covered' => ['required', 'string', 'min:10'],
            'voyage_from' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_to' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_via' => ['required', 'string', 'min:2', 'max:255'],
            'amount_insured_usd' => ['required', 'numeric'],
            'amount_insured_tolerance' => ['required', 'numeric'],
            'usd_to_bdt_rate' => ['required', 'numeric'],
            'mr_no' => ['required', 'numeric'],
            'vat_rate' => ['required', 'numeric'],
            'stamp_duty_bdt' => ['required', 'numeric'],
        ];
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function render()
    {
        return view('livewire.cover-notes.create');
    }
}

app/Http/Livewire/CoverNotes/Edit.php
<?php

namespace App\Http\Livewire\CoverNotes;

use Livewire\Component;

class Edit extends Component
{
    public $coverNote;
    public $branches;
    public $risks;
    public $transits;
    public $issuing_office;
    public $insured_bank_name;
    public $insured_bank_address;
    public $insured_bank_account_name;
    public $insured_address;
    public $interest_covered;
    public $voyage_from;
    public $voyage_to;
    public $voyage_via;
    public $amount_insured_usd;
    public $amount_insured_tolerance;
    public $usd_to_bdt_rate;
    public $mr_no;
    public $vat_rate;
    public $stamp_duty_bdt;

    protected function rules()
    {
        return [
            'issuing_office' => ['required', 'string'],
            'insured_bank_name' => ['required', 'string', 'min:2', 'max:255'],
            'insured_bank_address' => ['required', 'string', 'min:10', 'max:255'],
            'insured_bank_account_name' => ['required', 'string', 'max:255'],
            'insured_address' => ['required', 'string', 'min:10', 'max:255'],
            'interest_covered' => ['required', 'string', 'min:10'],
            'voyage_from' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_to' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_via' => ['required', 'string', 'min:2', 'max:255'],
            'amount_insured_usd' => ['required', 'numeric'],
            'amount_insured_tolerance' => ['required', 'numeric'],
            'usd_to_bdt_rate' => ['required', 'numeric'],
            'mr_no' => ['required', 'numeric'],
            'vat_rate' => ['required', 'numeric'],
            'stamp_duty_bdt' => ['required', 'numeric'],
        ];
    }

    public function mount()
	{
		$this->fill([
            'issuing_office' => $this->coverNote->issuing_office_id,
            'insured_bank_name' => $this->coverNote->insured_bank_name,
            'insured_bank_address' => $this->coverNote->insured_bank_address,
            'insured_bank_account_name' => $this->coverNote->insured_bank_account_name,
            'insured_address' => $this->coverNote->insured_address,
            'interest_covered' => $this->coverNote->interest_covered,
            'voyage_from' => $this->coverNote->voyage_from,
            'voyage_to' => $this->coverNote->voyage_to,
            'voyage_via' => $this->coverNote->voyage_via,
            'amount_insured_usd' => $this->coverNote->amount_insured_usd,
            'amount_insured_tolerance' => $this->coverNote->amount_insured_tolerance,
            'usd_to_bdt_rate' => $this->coverNote->usd_to_bdt_rate,
            'mr_no' => $this->coverNote->mr_no,
            'vat_rate' => $this->coverNote->vat_rate,
            'stamp_duty_bdt' => $this->coverNote->stamp_duty_bdt
		]);
	}

    public function render()
    {
        return view('livewire.cover-notes.edit');
    }
}

app/Http/Livewire/Risks/Create.php
<?php

namespace App\Http\Livewire\Risks;

use Livewire\Component;

class Create extends Component
{
    public $name;
	public $tariff;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255','unique:risks'],
            'tariff' => ['required', 'numeric'],
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.risks.create');
    }
}

app/Http/Livewire/Risks/Edit.php
<?php

namespace App\Http\Livewire\Risks;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $risk, $name, $tariff;

	public function mount()
	{
		$this->fill([
			'name' => $this->risk->name,
            'tariff' => $this->risk->tariff,
		]);
	}

	protected function rules()
	{
		return [
        	'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('risks')->ignore($this->risk)],
            'tariff' => ['required', 'numeric'],
        ];
	}

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.risks.edit');
    }
}

app/Http/Livewire/Transits/Create.php
<?php

namespace App\Http\Livewire\Transits;

use Livewire\Component;

class Create extends Component
{
	public $name;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255','unique:transits']
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.transits.create');
    }
}

app/Http/Livewire/Transits/Edit.php
<?php

namespace App\Http\Livewire\Transits;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $transit, $name;

	public function mount()
	{
		$this->fill([
			'name' => $this->transit->name,
		]);
	}

	protected function rules()
	{
        return [
        	'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('transits')->ignore($this->transit)]
        ];
	}

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.transits.edit');
    }
}

app/Http/Livewire/Users/Create.php
<?php

namespace App\Http\Livewire\Users;

use App\Models\User;
use Livewire\Component;

class Create extends Component
{
	public $name, $email, $password, $password_confirmation;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.create');
    }
}

app/Http/Livewire/Users/Edit.php
<?php

namespace App\Http\Livewire\Users;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $user, $name, $email, $password, $password_confirmation;

	public function mount()
	{
		$this->fill([
			'name' => $this->user->name,
			'email' => $this->user->email
		]);
	}

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($this->user)],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.edit');
    }
}

resources/views/livewire/cover-notes/create.blade.php
<form class="form-horizontal" action="{{ route('cover-notes.store') }}" method="post">
  @csrf
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="issuing_office">Issuing Office</label>
    <div class="col-md-9">
      <select class="form-control" id="issuing_office" name="issuing_office" wire:model="issuing_office" autocomplete="off">
        <option value="" hidden selected>Please Select</option>
      	@foreach ($branches as $branch)
      		<option value="{{ $branch->id }}">{{ $branch->name }}</option>
      	@endforeach
      </select>
      @error('issuing_office') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="insured_bank_name">Insured Bank Name</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="insured_bank_name" id="insured_bank_name" name="insured_bank_name" type="text" placeholder="name of the insured bank">
      @error('insured_bank_name') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="insured_bank_address">Insured Bank Address</label>
    <div class="col-md-9">
      <textarea class="form-control" wire:model="insured_bank_address" id="insured_bank_address" name="insured_bank_address" rows="9" placeholder="address of the insured bank"></textarea>
      @error('insured_bank_address') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="insured_bank_account_name">Insured Bank Account Name</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="insured_bank_account_name" id="insured_bank_account_name" name="insured_bank_account_name" type="text" placeholder="name of the insured bank account">
      @error('insured_bank_account_name') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="insured_address">Insured Address</label>
    <div class="col-md-9">
      <textarea class="form-control" wire:model="insured_address" id="insured_address" name="insured_address" rows="9" placeholder="address of the insured"></textarea>
      @error('insured_address') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="interest_covered">Interest Covered</label>
    <div class="col-md-9">
      <textarea class="form-control" wire:model="interest_covered" id="interest_covered" name="interest_covered" type="text"></textarea>
      @error('interest_covered') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="voyage_from">Voyage From</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="voyage_from" id="voyage_from" type="text" name="voyage_from">
      @error('voyage_from') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="voyage_to">Voyage To</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="voyage_to" id="voyage_to" type="text" name="voyage_to">
      @error('voyage_to') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="voyage_via">Voyage Via</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="voyage_via" id="voyage_via" type="text" name="voyage_via">
      @error('voyage_via') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>

  <div id="transportation">
    <div class="form-group row">
      <label class="col-md-3 col-form-label">Transits</label>
      <div class="col-md-9 col-form-label">
        @foreach ($transits as $transit)
          <div class="form-check form-check-inline mr-1">
            <input class="form-check-input" id="{{ $transit->id }}" name="transit{{ $transit->id }}" type="checkbox" value="{{ $transit->id }}" v-model="checkedTransits">
            <label class="form-check-label" for="{{ $transit->id }}">{{ $transit->name }}</label>
          </div>
        @endforeach
      </div>
    </div>
    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="carriage_id">Carriage</label>
      <div class="col-md-9">
        <select class="form-control" id="carriage_id" name="carriage_id" autocomplete="off">
          <option v-for="(carriageOption, index) in carriageOptions" :key="index+10" v-bind:value="carriageOption.id">
            @{{ carriageOption.name }}
          </option>
        </select>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label">Risks</label>
    <div class="col-md-9 col-form-label">
      @foreach($risks as $risk)
        <div class="form-check form-check-inline mr-1">
          <input class="form-check-input" id="{{ $risk->id }}" name="risk{{ $risk->id }}" type="checkbox" value="{{ $risk->id }}">
          <label class="form-check-label" for="{{ $risk->id }}">{{ $risk->name }}</label>
        </div>
      @endforeach
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="amount_insured_usd">Amount Insured (USD)</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="amount_insured_usd" id="amount_insured_usd" type="text" name="amount_insured_usd">
      @error('amount_insured_usd') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="amount_insured_tolerance">Amount Insured Tolerance (%)</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="amount_insured_tolerance" id="amount_insured_tolerance" type="text" name="amount_insured_tolerance">
      @error('amount_insured_tolerance') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="usd_to_bdt_rate">USD-BDT Coversion Rate</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="usd_to_bdt_rate" id="usd_to_bdt_rate" type="text" name="usd_to_bdt_rate" placeholder="enter equivalent amount of 1$ in tk">
      @error('usd_to_bdt_rate') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="period_starts">Period Starts</label>
    <div class="col-md-9">
      <input class="form-control" id="period_starts" type="date" name="period_starts">
      @error('period_starts') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="period_ends">Period Ends</label>
    <div class="col-md-9">
      <input class="form-control" id="period_ends" type="date" name="period_ends">
      @error('period_ends') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="mr_no">Money Receipt No.</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="mr_no" id="mr_no" type="text" name="mr_no">
      @error('mr_no') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="vat_rate">Vat Rate (BDT) (%)</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="vat_rate" id="vat_rate" type="text" name="vat_rate">
      @error('vat_rate') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="stamp_duty_bdt">Stamp Duty (BDT)</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="stamp_duty_bdt" id="stamp_duty_bdt" type="text" name="stamp_duty_bdt">
      @error('stamp_duty_bdt') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="card-footer">
    <button class="btn btn-sm btn-primary" type="submit"> Submit</button>
    <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
  </div>
</form>