routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/', 'IndexController')->name('index');
	Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs.index')->middleware('can:view logs');
	Route::get('users/{user}/permissons', 'UserController@showPermissions')->name('users.showPermissions');
	Route::post('users/{user}/permissons/', 'UserController@givePermissions')->name('users.givePermissions');
	Route::resource('users', 'UserController');
	Route::resource('branches', 'BranchController');
	Route::resource('transits', 'TransitController');
	Route::resource('risks', 'RiskController');
	Route::post('/cover-notes/{coverNote}/download', 'CoverNoteController@download')->name('cover-notes.download');
	Route::resource('cover-notes', 'CoverNoteController')->parameters(['cover-notes' => 'coverNote']);
});

app/Models/Branch.php
<?php

namespace App\Models;

use App\Traits\UuidTrait;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
	use UuidTrait;

    protected $fillable = [
		'name',
		'address',
		'phone_number',
		'fax_number',
		'email',
    ];
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Branch;
use App\Http\Requests\BranchRequest;
use Illuminate\Support\Facades\{
    View,
    Redirect,
};

class BranchController extends Controller
{
    private $branch;

    function __construct(Branch $branch)
    {
        $this->branch = $branch;
    
        $this->authorizeResource(Branch::class, 'branch');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = $this->branch->paginate(15);

        return View::make('branches.index', compact('branches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('branches.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\BranchRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BranchRequest $request)
    {
        $branch = $this->branch->create([
            'name' => request('name'),
            'email' => request('email'),
            'phone_number' => request('phone_number'),
            'fax_number' => request('fax_number'),
            'address' => request('address')
        ]);

        return Redirect::route('branches.show', $branch->id)->with('status', 'Branch created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show(Branch $branch)
    {
        return View::make('branches.show', compact('branch'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit(Branch $branch)
    {
        return View::make('branches.edit', compact('branch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\BranchRequest  $request
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(BranchRequest $request, Branch $branch)
    {
        $branch->update([
            'name' => request('name'),
            'email' => request('email'),
            'phone_number' => request('phone_number'),
            'fax_number' => request('fax_number'),
            'address' => request('address')
        ]);

        return Redirect::route('branches.show', $branch->id)->with('status', 'Branch updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        $branch->delete();

        return Redirect::route('branches.index')->with('status', 'Branch Deleted.');
    }
}

app/Http/Livewire/Branches/Create.php
<?php

namespace App\Http\Livewire\Branches;

use Livewire\Component;

class Create extends Component
{
	public $name, $email, $address, $phone_number, $fax_number;

	protected function rules()
    {
        return [
            'name' => 'required|string|min:2|max:255|unique:branches',
            'address' => 'required|string|min:10',
            'phone_number' => 'required|string|max:20|unique:branches',
            'fax_number' => 'required|string|max:20|unique:branches',
            'email' => ['required', 'string', 'email', 'max:255', 'unique:branches']
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.branches.create');
    }
}

app/Http/Livewire/Branches/Edit.php
<?php

namespace App\Http\Livewire\Branches;

use Livewire\Component;
use Illuminate\Validation\Rule;

class Edit extends Component
{
	public $branch, $name, $email, $address, $phone_number, $fax_number;

	public function mount()
	{
		$this->fill([
			'name' => $this->branch->name,
			'email' => $this->branch->email,
			'address' => $this->branch->address,
			'phone_number' => $this->branch->phone_number,
			'fax_number' => $this->branch->fax_number
		]);
	}

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('branches')->ignore($this->branch)],
            'address' => ['required', 'string', 'min:10'],
            'phone_number' => ['required', 'string', 'max:20', Rule::unique('branches')->ignore($this->branch)],
            'fax_number' => ['required', 'string', 'max:20',  Rule::unique('branches')->ignore($this->branch)],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('branches')->ignore($this->branch)]
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.branches.edit');
    }
}

app/Http/Livewire/CoverNotes/Create.php
<?php

namespace App\Http\Livewire\CoverNotes;

use Livewire\Component;

class Create extends Component
{
    public $branches;
    public $risks;
    public $transits;
    public $issuing_office;
    public $insured_bank_name;
	public $insured_bank_address;
	public $insured_bank_account_name;
	public $insured_address;
	public $interest_covered;
	public $voyage_from;
	public $voyage_to;
	public $voyage_via;
	public $amount_insured_usd;
	public $amount_insured_tolerance;
	public $usd_to_bdt_rate;
	public $mr_no;
	public $vat_rate;
	public $stamp_duty_bdt;

    protected function rules()
    {
        return [
            'issuing_office' => ['required', 'string'],
            'insured_bank_name' => ['required', 'string', 'min:2', 'max:255'],
            'insured_bank_address' => ['required', 'string', 'min:10', 'max:255'],
            'insured_bank_account_name' => ['required', 'string', 'max:255'],
            'insured_address' => ['required', 'string', 'min:10', 'max:255'],
            'interest_covered' => ['required', 'string', 'min:10'],
            'voyage_from' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_to' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_via' => ['required', 'string', 'min:2', 'max:255'],
            'amount_insured_usd' => ['required', 'numeric'],
            'amount_insured_tolerance' => ['required', 'numeric'],
            'usd_to_bdt_rate' => ['required', 'numeric'],
            'mr_no' => ['required', 'numeric'],
            'vat_rate' => ['required', 'numeric'],
            'stamp_duty_bdt' => ['required', 'numeric'],
        ];
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function render()
    {
        return view('livewire.cover-notes.create');
    }
}

app/Http/Livewire/CoverNotes/Edit.php
<?php

namespace App\Http\Livewire\CoverNotes;

use Livewire\Component;

class Edit extends Component
{
    public $coverNote;
    public $branches;
    public $risks;
    public $transits;
    public $issuing_office;
    public $insured_bank_name;
    public $insured_bank_address;
    public $insured_bank_account_name;
    public $insured_address;
    public $interest_covered;
    public $voyage_from;
    public $voyage_to;
    public $voyage_via;
    public $amount_insured_usd;
    public $amount_insured_tolerance;
    public $usd_to_bdt_rate;
    public $mr_no;
    public $vat_rate;
    public $stamp_duty_bdt;

    protected function rules()
    {
        return [
            'issuing_office' => ['required', 'string'],
            'insured_bank_name' => ['required', 'string', 'min:2', 'max:255'],
            'insured_bank_address' => ['required', 'string', 'min:10', 'max:255'],
            'insured_bank_account_name' => ['required', 'string', 'max:255'],
            'insured_address' => ['required', 'string', 'min:10', 'max:255'],
            'interest_covered' => ['required', 'string', 'min:10'],
            'voyage_from' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_to' => ['required', 'string', 'min:2', 'max:255'],
            'voyage_via' => ['required', 'string', 'min:2', 'max:255'],
            'amount_insured_usd' => ['required', 'numeric'],
            'amount_insured_tolerance' => ['required', 'numeric'],
            'usd_to_bdt_rate' => ['required', 'numeric'],
            'mr_no' => ['required', 'numeric'],
            'vat_rate' => ['required', 'numeric'],
            'stamp_duty_bdt' => ['required', 'numeric'],
        ];
    }

    public function mount()
	{
		$this->fill([
            'issuing_office' => $this->coverNote->issuing_office_id,
            'insured_bank_name' => $this->coverNote->insured_bank_name,
            'insured_bank_address' => $this->coverNote->insured_bank_address,
            'insured_bank_account_name' => $this->coverNote->insured_bank_account_name,
            'insured_address' => $this->coverNote->insured_address,
            'interest_covered' => $this->coverNote->interest_covered,
            'voyage_from' => $this->coverNote->voyage_from,
            'voyage_to' => $this->coverNote->voyage_to,
            'voyage_via' => $this->coverNote->voyage_via,
            'amount_insured_usd' => $this->coverNote->amount_insured_usd,
            'amount_insured_tolerance' => $this->coverNote->amount_insured_tolerance,
            'usd_to_bdt_rate' => $this->coverNote->usd_to_bdt_rate,
            'mr_no' => $this->coverNote->mr_no,
            'vat_rate' => $this->coverNote->vat_rate,
            'stamp_duty_bdt' => $this->coverNote->stamp_duty_bdt
		]);
	}

    public function render()
    {
        return view('livewire.cover-notes.edit');
    }
}

app/Http/Livewire/Risks/Create.php
<?php

namespace App\Http\Livewire\Risks;

use Livewire\Component;

class Create extends Component
{
    public $name;
	public $tariff;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255','unique:risks'],
            'tariff' => ['required', 'numeric'],
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.risks.create');
    }
}

app/Http/Livewire/Risks/Edit.php
<?php

namespace App\Http\Livewire\Risks;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $risk, $name, $tariff;

	public function mount()
	{
		$this->fill([
			'name' => $this->risk->name,
            'tariff' => $this->risk->tariff,
		]);
	}

	protected function rules()
	{
		return [
        	'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('risks')->ignore($this->risk)],
            'tariff' => ['required', 'numeric'],
        ];
	}

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.risks.edit');
    }
}

app/Http/Livewire/Transits/Create.php
<?php

namespace App\Http\Livewire\Transits;

use Livewire\Component;

class Create extends Component
{
	public $name;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'min:2', 'max:255','unique:transits']
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.transits.create');
    }
}

app/Http/Livewire/Transits/Edit.php
<?php

namespace App\Http\Livewire\Transits;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $transit, $name;

	public function mount()
	{
		$this->fill([
			'name' => $this->transit->name,
		]);
	}

	protected function rules()
	{
        return [
        	'name' => ['required', 'string', 'min:2', 'max:255', Rule::unique('transits')->ignore($this->transit)]
        ];
	}

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);
	}

    public function render()
    {
        return view('livewire.transits.edit');
    }
}

app/Http/Livewire/Users/Create.php
<?php

namespace App\Http\Livewire\Users;

use App\Models\User;
use Livewire\Component;

class Create extends Component
{
	public $name, $email, $password, $password_confirmation;

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.create');
    }
}

app/Http/Livewire/Users/Edit.php
<?php

namespace App\Http\Livewire\Users;

use Illuminate\Validation\Rule;
use Livewire\Component;

class Edit extends Component
{
	public $user, $name, $email, $password, $password_confirmation;

	public function mount()
	{
		$this->fill([
			'name' => $this->user->name,
			'email' => $this->user->email
		]);
	}

	protected function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($this->user)],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'password_confirmation' => 'required',
        ];
    }

	public function updated($propertyName)
	{
		$this->validateOnly($propertyName);

        $propertyName == 'password_confirmation' ? $this->validateOnly('password') : null;
	}

    public function render()
    {
        return view('livewire.users.edit');
    }
}

resources/views/livewire/branches/create.blade.php
<form class="form-horizontal" action="{{ route('branches.store') }}" method="post">
  @csrf
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="name">Name</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="name" id="name" type="text" name="name" placeholder="name of the branch">
      @error('name') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="email">Email</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="email" id="email" type="email" name="email" placeholder="something@example.com" autocomplete="email">
      @error('email') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="phone_number">Phone Number</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="phone_number" id="phone_number" type="text" name="phone_number" placeholder="phone no. of the branch">
      @error('phone_number') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="fax_number">Fax Number</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="fax_number" id="fax_number" type="text" name="fax_number" placeholder="fax no. of the branch">
      @error('fax_number') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="address">Address</label>
    <div class="col-md-9">
      <textarea class="form-control" wire:model="address" id="address" name="address" rows="9" placeholder="address of the branch"></textarea>
      @error('address') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="card-footer">
    <button class="btn btn-sm btn-primary" type="submit"> Submit</button>
    <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
  </div>
</form>

resources/views/livewire/branches/edit.blade.php
<form class="form-horizontal" action="{{ route('branches.update', $branch->id) }}" method="post">
  @method('PATCH')
  @csrf
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="name">Name</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="name" id="name" type="text" name="name" placeholder="name of the branch">
      @error('name') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="email">Email</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="email" id="email" type="email" name="email" placeholder="something@example.com" autocomplete="email">
      @error('email') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="phone_number">Phone Number</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="phone_number" id="phone_number" type="text" name="phone_number" placeholder="phone no. of the branch">
      @error('phone_number') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="fax_number">Fax Number</label>
    <div class="col-md-9">
      <input class="form-control" wire:model="fax_number" id="fax_number" type="text" name="fax_number" placeholder="fax no. of the branch">
      @error('fax_number') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="address">Address</label>
    <div class="col-md-9">
      <textarea class="form-control" wire:model="address" id="address" name="address" rows="9" placeholder="address of the branch"></textarea>
      @error('address') <span class="error">{{ $message }}</span> @enderror
    </div>
  </div>
  <div class="card-footer">
    <button class="btn btn-sm btn-primary" type="submit"> Submit</button>
    <button class="btn btn-sm btn-danger" type="reset"> Reset</button>
  </div>
</form>